name: Publish to Atom.io

on:
  release:
    types: [ published ]

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      ATOM_ACCESS_TOKEN: ${{ secrets.APM_TOKEN }}
    steps:
    - uses: actions/checkout@v1
    - uses: UziTech/action-setup-atom@v2
      with:
        version: stable
    - name: Get Tag
      run: cut -d / -f 3 <<< $GITHUB_REF > tag.txt
    - name: Publish
      run: apm publish --tag `cat tag.txt`
